package presentacion.comando;


public enum IDEventos {
	
	//CLIENTE
	 EVENTO_ALTA_CLIENTE,
	 ERROR_EVENTO_ALTA_CLIENTE,
	 EVENTO_BAJA_CLIENTE,
	 ERROR_EVENTO_BAJA_CLIENTE,
	 EVENTO_CONSULTAR_UN_CLIENTE,
	 ERROR_EVENTO_CONSULTAR_UN_CLIENTE,
	 EVENTO_LISTAR_CLIENTES,
	 ERROR_EVENTO_LISTAR_CLIENTES,
	 EVENTO_MODIFICAR_CLIENTE,
	 ERROR_EVENTO_MODIFICAR_CLIENTE,
	 EVENTO_TOP_TEN_CLIENTES,
	 ERROR_EVENTO_TOP_TEN_CLIENTES, 
	
		
	//PRODUCTO 
	 EVENTO_ALTA_PRODUCTO,
	 ERROR_EVENTO_ALTA_PRODUCTO,
	 EVENTO_BAJA_PRODUCTO,
	 ERROR_EVENTO_BAJA_PRODUCTO,
	 EVENTO_CONSULTAR_UN_PRODUCTO,
	 ERROR_EVENTO_CONSULTAR_UN_PRODUCTO,
	 EVENTO_LISTAR_PRODUCTOS,
	 ERROR_EVENTO_LISTAR_PRODUCTOS,
	 EVENTO_MODIFICAR_PRODUCTO,
	 ERROR_EVENTO_MODIFICAR_PRODUCTO,
	 EVENTO_TOP_PRODUCTO,
	 ERROR_EVENTO_TOP_PRODUCTO,
	
	
	 //VENTA
	 EVENTO_ABRIR_VENTA,
	 ERROR_EVENTO_ABRIR_VENTA,
	 EVENTO_CERRAR_VENTA,
	 ERROR_EVENTO_CERRAR_VENTA,
	 EVENTO_CONSULTAR_UNA_VENTA,
	 ERROR_EVENTO_CONSULTAR_UNA_VENTA,
	 EVENTO_LISTAR_VENTAS,
	 ERROR_EVENTO_LISTAR_VENTAS,
	 EVENTO_DEVOLUCION_VENTA,
	 ERROR_EVENTO_DEVOLUCION_VENTA,
	 EVENTO_ANADIR_PRODUCTO_CARRITO,
	 ERROR_EVENTO_ANADIR_PRODUCTO_CARRITO,
	 EVENTO_ELIMINAR_PRODUCTO_CARRITO,
	 ERROR_EVENTO_ELIMINAR_PRODUCTO_CARRITO,
	 
}
